<div class="row">
    <div class="col-md-5">
        <div class="panel panel-default">
            <div class="panel-body">   
                <div class="panel-heading">Directives</div>
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Directive</th>
                                <th>Value</th>
                                <th>&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->directives as $key => $value): ?>
                                <tr>
                                    <td><?php echo $key; ?></td>
                                    <td><?php echo $value; ?></td>                                    
                                    <td><a href="http://php.net/manual/en/opcache.configuration.php#ini.<?php echo $key; ?>" target="_php-manual"><span class="glyphicon glyphicon-bookmark" aria-hidden="true"></span></a></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>                        
                    </table>   
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-body">   
                <div class="panel-heading">Functions</div>
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Function</th>
                                <th>&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->functions as $function): ?>
                                <tr>
                                    <td><?php echo $function['name']; ?></td>
                                    <td><a href="<?php echo $function['link']; ?>" target="_php-manual"><span class="glyphicon glyphicon-bookmark" aria-hidden="true"></span></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>                        
                    </table>   
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-body">   
                <div class="panel-heading">Opcache Version</div>

                <div class="table-responsive">

                    <table class="table table-striped table-hover" style="width:100%">
                        <thead>
                            <tr>
                                <th>Setting </th>
                                <th>Value</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Version</td>
                                <td><?php echo $version["version"]; ?></td>
                            </tr>
                            <tr>
                                <td>Product Name</td>
                                <td><?php echo $version["opcache_product_name"]; ?></td>
                            </tr>
                        </tbody>                        
                    </table>   
                </div>
            </div>
        </div>
    </div>
</div>
