<div class="row">
    <div class="col-md-12">
        <div id="ContentTabs-Scripts-Details" class="panel panel-default">
            <div class="panel-body">   
                <div class="panel-heading">Scripts
                    <h6 id="ScriptsTableListDisplayed" class="pull-right"></h6>
                </div>
                <table id="ScriptsTableList" class="table table-striped table-hover " style="width:100%">
                    <thead>
                        <tr>
                            <th style="padding-left:0;">
                                <div class="btn-group" style="width:100%;">
                                    <input id="searchInput" type="search" class="form-control" placeholder="Filter Results">
                                    <span id="searchClear" class="glyphicon glyphicon-remove-circle"></span>
                                </div>
                            </th>
                            <th class="details hidden-xs">Details</th>
                            <th><a href="#" id="btnScriptDetails" type="button" data-tab="overview" class="btn btn-sm btn-default hidden-xs"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>&nbsp;Details</a></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->scripts as $script): ?>
                            <tr>
                                <td class="ScriptName" style="word-break:break-all;"><?php echo $script['full_path']; ?></td>
                                <td class="details text-nowrap hidden-xs">
                                    <small>
                                        <strong>Hits:</strong> <?php echo $script['hits']; ?><br/>
                                        <strong>Memory Usage:</strong> <?php echo $this->FormatMemorySize($script['memory_consumption']); ?><br/>
                                        <strong>Time:</strong> <?php echo date("d/m/Y @ H:i:s", $script['timestamp']); ?><br/>
                                        <strong>Last Used:</strong> <?php echo date("d/m/Y @ H:i:s", $script['last_used_timestamp']); ?>
                                    </small>
                                </td>
                                <td style="vertical-align: middle;"><button type="button" class="btn btn-primary btn-sm btnInvalidate">Invalidate</button></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>                        
                </table>   

            </div>
        </div>
    </div>
</div>
