<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <title>CPC Opacache - About</title>  
    </head>
    <body>
        <div class="modal-header ">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">CPC Opcache</h4>
        </div>
        <div class="modal-body">
            <p>A PHP Opcache management tool created to allow me to manage a projects Opcache from my android tablet</p>

            <p>Libraries Used:</p>
            <ul>
                <li>Zend Expressive</li>
                <li>Zend Framework</li>
                <li>Jquery</li>
                <li>Bootstrap</li>
            </ul>
            <p>Gareth C Matthews 2016 gareth@crossplatformcoder.com (<a href="http://www.crossplatformcoder.com" target="_blank">Crossplatformcoder</a>)</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
        </div>
    </body>
</html>
